// style
import "./globals.css";
import { Ubuntu, Kanit, Alkatra } from "next/font/google";
// next
import type { Metadata } from "next";
// component
import { ThemeProvider } from "@/components/theme/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import { ScrollTop } from "@/components";
// i18n

import { Locale } from "@/lib/i18n.config";
import Navbar from "@/components/navbar/Navbar";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  variable: "--font-ubuntu",
  weight: ["300", "400", "500", "700"],
});
const kanit = Kanit({
  subsets: ["latin"],
  variable: "--font-kanit",
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});
const alkatra = Alkatra({
  subsets: ["latin"],
  variable: "--font-alkatra",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Ali Seyedi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {
  return (
    <html lang={params.lang}>
      <body className={` ${ubuntu.variable} ${alkatra.variable} ${kanit.variable} `}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {/* <Header lang={params.lang} /> */}
          <Navbar lang={params.lang} />
          {children}
          <ScrollTop />
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
