export { default as Home } from "./home/Home";
export { default as About } from "./about/About";
export { default as Skills } from "./skills/Skills";
export { default as Projects } from "./projects/Projects";
export { default as Resume } from "./resume/Resume";
export { default as Contact } from "./contact/Contact";
export { default as ScrollTop } from "./utility/ScrollTop";
export { default as BackPage } from "./utility/BackPage";
export { default as LanguageSwitcher } from "./navbar/LanguageSwitcher";
